// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8WMIIdJZ9jH93PHHCX7oUAHGyC1-7w_Y',
    appId: '1:3733963412:web:24d4f2c81013d19f6b6a81',
    messagingSenderId: '3733963412',
    projectId: 'jydaclean1-5c3a8',
    authDomain: 'jydaclean1-5c3a8.firebaseapp.com',
    storageBucket: 'jydaclean1-5c3a8.firebasestorage.app',
    measurementId: 'G-BGLHPGKMMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePaSomF70eS30ardEA0OJxkn2jTjwup0',
    appId: '1:3733963412:android:4f255de13f986c216b6a81',
    messagingSenderId: '3733963412',
    projectId: 'jydaclean1-5c3a8',
    storageBucket: 'jydaclean1-5c3a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNhxOzDSKId57CgXEmr6XbVHdp-Z-5Q4',
    appId: '1:3733963412:ios:dfcac83a9a43db8c6b6a81',
    messagingSenderId: '3733963412',
    projectId: 'jydaclean1-5c3a8',
    storageBucket: 'jydaclean1-5c3a8.firebasestorage.app',
    iosBundleId: 'com.example.jydaclean1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNhxOzDSKId57CgXEmr6XbVHdp-Z-5Q4',
    appId: '1:3733963412:ios:dfcac83a9a43db8c6b6a81',
    messagingSenderId: '3733963412',
    projectId: 'jydaclean1-5c3a8',
    storageBucket: 'jydaclean1-5c3a8.firebasestorage.app',
    iosBundleId: 'com.example.jydaclean1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8WMIIdJZ9jH93PHHCX7oUAHGyC1-7w_Y',
    appId: '1:3733963412:web:2aff19a6e4bfc0b36b6a81',
    messagingSenderId: '3733963412',
    projectId: 'jydaclean1-5c3a8',
    authDomain: 'jydaclean1-5c3a8.firebaseapp.com',
    storageBucket: 'jydaclean1-5c3a8.firebasestorage.app',
    measurementId: 'G-RG7HJTTKG1',
  );
}
